<a href="https://colab.research.google.com/github/Shi-Yile/SPH6004-Assignment-1/blob/main/code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# Import packages

# Data-processing packages
import pandas as pd
import numpy as np

# Plotting packages
import matplotlib.pyplot as plt
import seaborn as sn

# ML packages
import sklearn

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import mutual_info_classif

from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, StratifiedKFold, cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

from sklearn.metrics import roc_auc_score, roc_curve, classification_report, confusion_matrix, recall_score, accuracy_score, f1_score


import os
from google.colab import drive

In [53]:
# give permission to load data from google drive
drive.mount('/content/drive')
os.chdir('drive/My Drive/SPH6004/Assignment-1')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/SPH6004/Assignment-1'

In [54]:
# load dataset
df = pd.read_csv('data.csv')
df_origin = df.copy()
df.head()

id  aki gender  admission_age                    race  \
0  36570066    3      F      79.953141  BLACK/AFRICAN AMERICAN   
1  39307659    0      F      78.194169         WHITE - RUSSIAN   
2  38743306    2      F      65.602396                   WHITE   
3  32339865    2      F      64.906629                 UNKNOWN   
4  35526987    2      M      57.438861                   WHITE   

   heart_rate_min  heart_rate_max  heart_rate_mean  sbp_min  sbp_max  ...  \
0            96.0           104.0       100.083333    103.0    126.0  ...   
1            72.0           134.0        97.263158     97.0    127.0  ...   
2            60.0            97.0        84.166667     95.0    143.0  ...   
3            59.0            87.0        71.461538    113.0    150.0  ...   
4            57.0           100.0        82.387097     81.0    127.0  ...   

   ggt_max  ld_ldh_min  ld_ldh_max  gcs_min  gcs_motor  gcs_verbal  gcs_eyes  \
0      NaN       236.0       318.0     15.0        6.0         5.0       4.0   
1      NaN         NaN         NaN     15.0        6.0         5.0       4.0   
2      NaN         NaN         NaN     15.0        6.0         5.0       4.0   
3      NaN         NaN         NaN     15.0        1.0         0.0       1.0   
4      NaN         NaN         NaN     15.0        NaN         0.0       1.0   

   gcs_unable  height  weight_admit  
0         0.0   157.0         110.0  
1         0.0     NaN          82.0  
2         0.0     NaN          62.1  
3         1.0   170.0         113.1  
4         1.0   178.0          97.4  

[5 rows x 162 columns]

In [55]:
# basic infomration of each column in df
df.info(verbose = True, null_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50920 entries, 0 to 50919
Data columns (total 162 columns):
 #    Column                  Non-Null Count  Dtype  
---   ------                  --------------  -----  
 0    id                      50920 non-null  int64  
 1    aki                     50920 non-null  int64  
 2    gender                  50920 non-null  object 
 3    admission_age           50920 non-null  float64
 4    race                    50920 non-null  object 
 5    heart_rate_min          50841 non-null  float64
 6    heart_rate_max          50841 non-null  float64
 7    heart_rate_mean         50841 non-null  float64
 8    sbp_min                 50823 non-null  float64
 9    sbp_max                 50823 non-null  float64
 10   sbp_mean                50823 non-null  float64
 11   dbp_min                 50823 non-null  float64
 12   dbp_max                 50823 non-null  float64
 13   dbp_mean                50823 non-null  float64
 14   mbp_min             

<ipython-input-55-1fc94d2bc7dc>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  df.info(verbose = True, null_counts = True)


In [56]:
# frequencies in 'race'
df['race'].value_counts()

WHITE                                        32637
UNKNOWN                                       5579
BLACK/AFRICAN AMERICAN                        3845
OTHER                                         1745
WHITE - OTHER EUROPEAN                         918
UNABLE TO OBTAIN                               726
ASIAN                                          614
ASIAN - CHINESE                                547
HISPANIC/LATINO - PUERTO RICAN                 530
HISPANIC OR LATINO                             501
WHITE - RUSSIAN                                430
PATIENT DECLINED TO ANSWER                     371
HISPANIC/LATINO - DOMINICAN                    337
BLACK/CAPE VERDEAN                             319
BLACK/CARIBBEAN ISLAND                         282
BLACK/AFRICAN                                  194
ASIAN - SOUTH EAST ASIAN                       168
PORTUGUESE                                     161
ASIAN - ASIAN INDIAN                           121
WHITE - EASTERN EUROPEAN       

In [57]:
# re-catergorize 'race' with fewer levels, and create dummy variables
# white, black, asian, hispanic/latino, other, unknown
# df['white'] = df['race'].apply(lambda x: 1 if 'WHITE' in x else 0)
df['race_white'] = df['race'].apply(lambda x: int('WHITE' in x))
df['race_black'] = df['race'].apply(lambda x: int('BLACK' in x))
df['race_asian'] = df['race'].apply(lambda x: int('ASIAN' in x))
df['race_hispanic/latino'] = df['race'].apply(
    lambda x: int('HISPANIC' in x or 'LATINO' in x))
df['race_unknown'] = df['race'].apply(lambda x: int(
    x == 'UNKNOWN' or x == 'UNABLE TO OBTAIN' or
    x == 'PATIENT DECLINED TO ANSWER'))
df['race_other'] = df['race'].apply(lambda x: int(
    x == 'OTHER' or x == 'PORTUGUESE' or
    x == 'AMERICAN INDIAN/ALASKA NATIVE' or
    x == 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER' or
    x == 'MULTIPLE RACE/ETHNICITY' or x == 'SOUTH AMERICAN'))

# frequency in each level
print('WHITE: ', df['race_white'].sum())
print('BLACK: ', df['race_black'].sum())
print('ASIAN: ', df['race_asian'].sum())
print('HISPANIC/LATINO: ', df['race_hispanic/latino'].sum())
print('OTHER: ', df['race_other'].sum())
print('UNKNOWN: ', df['race_unknown'].sum())

WHITE:  34204
BLACK:  4640
ASIAN:  1496
HISPANIC/LATINO:  1735
OTHER:  2169
UNKNOWN:  6676


In [58]:
# recode gender as 0-1  0: male, 1: female
df['gender_'] = df['gender'].apply(lambda x:int(x == 'F'))
df['gender_'].value_counts()

0    28440
1    22480
Name: gender_, dtype: int64

In [59]:
# re-categorise AKI as a binary column  0: aki = 0, 1: aki = 1/2/3
df['aki_'] = df['aki'].apply(
    lambda x:int(x == 1 or x == 2 or x == 3))
df['aki_'].value_counts()

1    34060
0    16860
Name: aki_, dtype: int64

In [60]:
# NA detected, thus need further processing including feature selection
# calculate the proportion of NAs in each column
df_NA_prop = 1 - df.count() / len(df)

# extract two sets of indices from df
# whose correpsonding columns including NAs less than 10% and 50%, respectively
idx_NA10 = df_NA_prop[df_NA_prop <= 0.1].index
idx_NA50 = df_NA_prop[df_NA_prop <= 0.5].index
# idx_NA10

# extract two subsets of df based on previous indices
df_sub_NA10 = df[idx_NA10]
df_sub_NA50 = df[idx_NA50]
# df_sub_NA10.info()

#  drop rows with NAs
df_sub_com10 = df_sub_NA10.dropna()
df_sub_com50 = df_sub_NA50.dropna()
# df_sub_com10.info()

In [61]:
# df_sub_com10.info()
# df_sub_NA50.info()

In [62]:
df_sub_com10['aki_'].value_counts()

1    26484
0    12147
Name: aki_, dtype: int64

In [63]:
df_sub_com50['aki_'].value_counts()

1    10569
0     2945
Name: aki_, dtype: int64

In [64]:
# create outcome vector and predictor matrix
# drop id and race first
df_10 = df_sub_com10.drop(columns = ['id', 'aki', 'race', 'gender'])
df_50 = df_sub_com50.drop(columns = ['id', 'aki', 'race', 'gender'])

In [65]:
# split dataset
# first we extract X and y

# df_10
y_df_10 = df_10['aki_']
X_df_10 = df_10.drop(columns = ['aki_'])

# df_50
y_df_50 = df_50['aki_']
X_df_50 = df_50.drop(columns = ['aki_'])

In [66]:
# compute the mutual information of each factor with aki_binary
# case: df_10
MI_df_10 = pd.DataFrame(
    data = mutual_info_classif(X_df_10, y_df_10),
    index = X_df_10.columns,
    columns = ['MI'])

MI_df_10.sort_values(by = 'MI', ascending = False).head(15)

MI
bun_min         0.024473
bun_max         0.023788
gcs_verbal      0.022617
glucose_mean    0.020666
pt_max          0.020373
inr_max         0.018942
resp_rate_mean  0.018653
admission_age   0.016598
pt_min          0.016187
weight_admit    0.015382
sbp_min         0.014897
glucose_max.2   0.014636
inr_min         0.014505
gcs_motor       0.014479
dbp_mean        0.014377

In [67]:
# factors with 0 MI with aki
MI_df_10[MI_df_10.MI == 0]

MI
sbp_max           0.0
hematocrit_max.1  0.0
calcium_max.1     0.0
race_black        0.0
race_unknown      0.0

In [68]:
# drop columns irrelated to aki
df_10.drop(columns = MI_df_10[MI_df_10.MI == 0].index, inplace = True)

In [69]:
# case: df_50
MI_df_50 = pd.DataFrame(
    data = mutual_info_classif(X_df_50, y_df_50),
    index = X_df_50.columns,
    columns = ['MI'])

MI_df_50.sort_values(by = 'MI', ascending = False).head(15)

MI
bun_min        0.029585
bun_max        0.024631
weight_admit   0.019904
spo2_min       0.015399
sbp_min        0.014644
pt_max         0.012990
admission_age  0.011205
gcs_eyes       0.010771
gcs_verbal     0.010558
ptt_max        0.010232
glucose_mean   0.010162
pt_min         0.009465
lactate_max    0.009403
gcs_motor      0.008913
sbp_mean       0.008701

In [70]:
# 0-MI factors
MI_df_50[MI_df_50.MI == 0]

MI
dbp_max               0.0
mbp_max               0.0
resp_rate_min         0.0
temperature_mean      0.0
lactate_min           0.0
totalco2_min          0.0
hematocrit_min.1      0.0
hematocrit_max.1      0.0
platelets_max         0.0
wbc_max               0.0
bicarbonate_max.1     0.0
chloride_max.1        0.0
glucose_min.2         0.0
sodium_min.1          0.0
abs_basophils_min     0.0
race_white            0.0
race_hispanic/latino  0.0
race_unknown          0.0

In [71]:
df_50.drop(columns = MI_df_50[MI_df_50.MI == 0].index, inplace = True)

In [72]:
# standardization on X: (X - mean) / std
# Std = StandardScaler(copy = False)
# X_std_df_10 = pd.DataFrame(
    # data = Std.fit_transform(X_df_10),
    # columns = Std.get_feature_names_out(input_features = X_df_10.columns))

# X_std_df_50 = pd.DataFrame(
    # data = Std.fit_transform(X_df_50),
    # columns = Std.get_feature_names_out(input_features = X_df_50.columns))

In [73]:
# training - test split
X_10_train, X_10_test, y_10_train, y_10_test = train_test_split(
    X_df_10, y_df_10, test_size = 0.3, random_state = 42,
    stratify = y_df_10, shuffle = True)

X_50_train, X_50_test, y_50_train, y_50_test = train_test_split(
    X_df_50, y_df_50, test_size = 0.3, random_state = 42,
    stratify = y_df_50, shuffle = True)

## Logistic Regression

In [81]:
# logistic regression with CV
lr_param = {
    'model__C': np.linspace(0.005, 0.05, 10),
}

In [82]:
# GridSearch with CV for best C
stratifiedCV = StratifiedKFold(n_splits = 3)
LR_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(
        class_weight = 'balanced',
        solver = 'saga',
        max_iter = 50000))
])


BestLR = GridSearchCV(
    LR_pipe,
    param_grid = lr_param,
    scoring = 'f1',
    cv = stratifiedCV,
    verbose = 1,
    n_jobs = -1
)

In [83]:
# case: df_10
BestLR.fit(X_10_train, y_10_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(class_weight='balanced',
                                                           max_iter=50000,
                                                           solver='saga'))]),
             n_jobs=-1,
             param_grid={'model__C': array([0.005, 0.01 , 0.015, 0.02 , 0.025, 0.03 , 0.035, 0.04 , 0.045,
       0.05 ])},
             scoring='f1', verbose=1)

In [84]:
print(BestLR.best_params_)
print(BestLR.best_score_)

{'model__C': 0.030000000000000006}
0.7357528727318594


In [85]:
y_10_BestLR_pred = BestLR.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestLR_pred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestLR_pred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[2563 1081]
 [2691 5255]]
            no aki      aki  accuracy  macro avg  weighted avg
precision     0.49     0.83      0.67       0.66          0.72
recall        0.70     0.66      0.67       0.68          0.67
f1-score      0.58     0.74      0.67       0.66          0.69
support    3644.00  7946.00      0.67   11590.00      11590.00


In [86]:
# case: df_50
BestLR.fit(X_50_train, y_50_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(class_weight='balanced',
                                                           max_iter=50000,
                                                           solver='saga'))]),
             n_jobs=-1,
             param_grid={'model__C': array([0.005, 0.01 , 0.015, 0.02 , 0.025, 0.03 , 0.035, 0.04 , 0.045,
       0.05 ])},
             scoring='f1', verbose=1)

In [87]:
print(BestLR.best_params_)
print(BestLR.best_score_)

{'model__C': 0.015000000000000003}
0.7590562884608115


In [88]:
y_50_BestLR_pred = BestLR.predict(X_50_test)

print(confusion_matrix(y_50_test, y_50_BestLR_pred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestLR_pred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[ 622  262]
 [1043 2128]]
           no aki      aki  accuracy  macro avg  weighted avg
precision    0.37     0.89      0.68       0.63          0.78
recall       0.70     0.67      0.68       0.69          0.68
f1-score     0.49     0.77      0.68       0.63          0.70
support    884.00  3171.00      0.68    4055.00       4055.00


# Tree-based Model

## Decision Tree

In [89]:
# Tree-base models
# decision tree
dtc_param = {'model__max_depth': [2, 3, 4, 5, 6, 7]}

In [92]:
Tree_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', DecisionTreeClassifier(
        criterion = 'entropy',
        class_weight = 'balanced'
    ))
])


BestDTC = GridSearchCV(
    Tree_pipe,
    param_grid = dtc_param,
    scoring = 'f1',
    cv = stratifiedCV
)

In [93]:
# case: df_10
BestDTC.fit(X_10_train, y_10_train)

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        DecisionTreeClassifier(class_weight='balanced',
                                                               criterion='entropy'))]),
             param_grid={'model__max_depth': [2, 3, 4, 5, 6, 7]}, scoring='f1')

In [94]:
print(BestDTC.best_params_)
print(BestDTC.best_score_)

{'model__max_depth': 2}
0.7589189330014632


In [95]:
y_10_BestDTCpred = BestDTC.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestDTCpred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestDTCpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[1753 1891]
 [1954 5992]]
            no aki      aki  accuracy  macro avg  weighted avg
precision     0.47     0.76      0.67       0.62          0.67
recall        0.48     0.75      0.67       0.62          0.67
f1-score      0.48     0.76      0.67       0.62          0.67
support    3644.00  7946.00      0.67   11590.00      11590.00


In [96]:
# case: df_50
BestDTC.fit(X_50_train, y_50_train)

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        DecisionTreeClassifier(class_weight='balanced',
                                                               criterion='entropy'))]),
             param_grid={'model__max_depth': [2, 3, 4, 5, 6, 7]}, scoring='f1')

In [97]:
print(BestDTC.best_params_)
print(BestDTC.best_score_)

{'model__max_depth': 2}
0.7544027250491357


In [98]:
y_50_BestDTCpred = BestDTC.predict(X_50_test)

print(confusion_matrix(y_50_test, y_50_BestDTCpred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestDTCpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[ 450  434]
 [ 769 2402]]
           no aki      aki  accuracy  macro avg  weighted avg
precision    0.37     0.85       0.7       0.61          0.74
recall       0.51     0.76       0.7       0.63          0.70
f1-score     0.43     0.80       0.7       0.61          0.72
support    884.00  3171.00       0.7    4055.00       4055.00


## Random Forest

In [ ]:
# random forest
rf_param = {
    'n_estimators': np.arange(start = 10, stop = 100, step = 10),
    'max_depth': np.arange(start = 2, stop = 10, step = 1)
}

In [ ]:
RFModel = RandomForestClassifier(
    criterion = 'entropy',
    class_weight = 'balanced'
    )
BestRF = GridSearchCV(
    RFModel,
    param_grid = rf_param,
    scoring = 'f1',
    cv = stratifiedCV,
    verbose = 1,
    n_jobs = -1
)

In [ ]:
BestRF.fit(X_10_train, y_10_train)

In [ ]:
print(BestRF.best_params_)
print(BestRF.best_score_)

In [ ]:
y_10_BestRFpred = BestRF.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestRFpred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestRFpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

In [ ]:
# case: df_50
BestRF.fit(X_50_train, y_50_train)

In [ ]:
print(BestRF.best_params_)
print(BestRF.best_score_)

In [ ]:
y_50_BestRFpred = BestRF.predict(X_50_test)

print(confusion_matrix(y_50_test, y_50_BestRFpred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestRFpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

## AdaBoost

In [ ]:
# adaboost
ada_param = {
    'n_estimators': [100, 200, 500],
    'learning_rate': np.arange(start = 0.05, stop = 0.25, step = 0.05)
}

In [ ]:
AdaBoostModel = AdaBoostClassifier()
BestAda = GridSearchCV(
    AdaBoostModel,
    param_grid = ada_param,
    scoring = 'f1',
    cv = stratifiedCV,
    verbose = 1,
    n_jobs = -1
)

In [ ]:
# case: df_10
BestAda.fit(X_10_train, y_10_train)

In [ ]:
print(BestAda.best_params_)
print(BestAda.best_score_)

In [ ]:
# feature importance
BestAda_10 = AdaBoostClassifier(n_estimators = 200, learning_rate = 0.1)
BestAda_10.fit(X_10_train, y_10_train)
FI_BestAda_10 = pd.DataFrame(
    data = BestAda_10.feature_importances_,
    index = X_10_train.columns,
    columns = ['FI']
)

In [ ]:
FI_BestAda_10.sort_values(by = 'FI', ascending = False).head(15)

In [ ]:
# unimportant features
FI_BestAda_10[FI_BestAda_10.FI == 0]

In [ ]:
y_10_BestAdapred = BestAda.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestAdapred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestAdapred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

In [ ]:
# case: df_50
BestAda.fit(X_50_train, y_50_train)

In [ ]:
print(BestAda.best_params_)
print(BestAda.best_score_)

In [ ]:
BestAda_50 = AdaBoostClassifier(n_estimators = 200, learning_rate = 0.2)
BestAda_50.fit(X_50_train, y_50_train)
FI_BestAda_50 = pd.DataFrame(
    data = BestAda_50.feature_importances_,
    index = X_50_train.columns,
    columns = ['FI']
)

In [ ]:
FI_BestAda_50.sort_values(by = 'FI', ascending = False).head(15)

In [ ]:
FI_BestAda_50[FI_BestAda_50.FI == 0]

In [ ]:
y_50_BestAdapred = BestAda.predict(X_50_test)

print(confusion_matrix(y_50_test, y_50_BestAdapred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestAdapred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

## XGBoost

In [99]:
# xgboost
xg_param = {
    'model__n_estimators': [100, 200, 500],
    'model__max_depth': np.arange(start = 2, stop = 5, step = 1),
    'model__learning_rate': np.arange(start = 0.01, stop = 0.1, step = 0.01)
}

In [110]:
XGBoost_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', XGBClassifier(importance_type = 'gain'))
])

BestXGBoost = GridSearchCV(
    estimator = XGBoost_pipe,
    param_grid = xg_param,
    scoring = 'f1',
    cv = stratifiedCV,
    verbose = 1,
    n_jobs = -1
)

In [111]:
# case: df_10
BestXGBoost.fit(X_10_train, y_10_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=False,
                                                      eval_metric=None,
                                                      featu...
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]),
                         'model__max_depth': array([2, 3, 4]),
                         'model__n_estimators': [100, 200, 500]},
             scoring='f1', verbose=1)

In [112]:
print(BestXGBoost.best_params_)
print(BestXGBoost.best_score_)

{'model__learning_rate': 0.02, 'model__max_depth': 4, 'model__n_estimators': 200}
0.8272823655868796


In [113]:
BestXGBoost_10 = XGBClassifier(learning_rate = 0.02, max_depth = 4,
                               n_estimators = 200, importance_type = 'gain')
BestXGBoost_10.fit(X_10_train, y_10_train)
FI_BestXGBoost_10 = pd.DataFrame(
    data = BestXGBoost_10.feature_importances_,
    index = X_10_train.columns,
    columns = ['FI']
)

In [114]:
FI_BestXGBoost_10.sort_values(by = 'FI', ascending = False).head(15)

FI
bun_max          0.095608
inr_max          0.076064
bun_min          0.061545
gcs_verbal       0.056649
gcs_unable       0.042725
glucose_max      0.031548
potassium_max.1  0.028598
admission_age    0.026312
weight_admit     0.025985
spo2_min         0.025952
sbp_min          0.025901
pt_max           0.024934
dbp_min          0.024313
gcs_eyes         0.018424
heart_rate_max   0.017186

In [115]:
FI_BestXGBoost_10[FI_BestXGBoost_10.FI == 0]

FI
race_black  0.0
race_asian  0.0
race_other  0.0

In [116]:
y_10_BestXGBpred = BestXGBoost.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestXGBpred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestXGBpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[1181 2463]
 [ 602 7344]]
            no aki      aki  accuracy  macro avg  weighted avg
precision     0.66     0.75      0.74       0.71          0.72
recall        0.32     0.92      0.74       0.62          0.74
f1-score      0.44     0.83      0.74       0.63          0.70
support    3644.00  7946.00      0.74   11590.00      11590.00


In [117]:
# case: df_50
BestXGBoost.fit(X_50_train, y_50_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=False,
                                                      eval_metric=None,
                                                      featu...
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]),
                         'model__max_depth': array([2, 3, 4]),
                         'model__n_estimators': [100, 200, 500]},
             scoring='f1', verbose=1)

In [118]:
print(BestXGBoost.best_params_)
print(BestXGBoost.best_score_)

{'model__learning_rate': 0.060000000000000005, 'model__max_depth': 2, 'model__n_estimators': 200}
0.8839386288153473


In [119]:
BestXGBoost_50 = XGBClassifier(learning_rate = 0.06, max_depth = 2,
                               n_estimators = 200, importance_type = 'gain')
BestXGBoost_50.fit(X_50_train, y_50_train)
FI_BestXGBoost_50 = pd.DataFrame(
    data = BestXGBoost_50.feature_importances_,
    index = X_50_train.columns,
    columns = ['FI']
)

In [120]:
FI_BestXGBoost_50.sort_values(by = 'FI', ascending = False).head(15)

FI
bun_min            0.096028
bun_max            0.075057
gcs_verbal         0.041731
ptt_max            0.030089
weight_admit       0.028388
gcs_eyes           0.023941
admission_age      0.021603
sbp_min            0.021516
pt_max             0.019538
abs_basophils_min  0.019293
pco2_max           0.018650
spo2_min           0.018121
potassium_max.1    0.018046
po2_max            0.018006
gcs_motor          0.017627

In [121]:
FI_BestXGBoost_50[FI_BestXGBoost_50.FI == 0]

FI
pco2_min              0.0
totalco2_min          0.0
platelets_max         0.0
wbc_min               0.0
bicarbonate_min.1     0.0
bicarbonate_max.1     0.0
sodium_max.1          0.0
potassium_min.1       0.0
abs_eosinophils_min   0.0
abs_eosinophils_max   0.0
inr_min               0.0
inr_max               0.0
gcs_min               0.0
gcs_unable            0.0
race_white            0.0
race_black            0.0
race_asian            0.0
race_hispanic/latino  0.0
race_unknown          0.0
race_other            0.0

In [ ]:
# plot_tree(BestXGBoost_50)

In [122]:
y_50_BestXGBpred = BestXGBoost.predict(X_50_test)

print(confusion_matrix(y_50_test, y_50_BestXGBpred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestXGBpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[ 135  749]
 [  65 3106]]
           no aki      aki  accuracy  macro avg  weighted avg
precision    0.68     0.81       0.8       0.74          0.78
recall       0.15     0.98       0.8       0.57          0.80
f1-score     0.25     0.88       0.8       0.57          0.75
support    884.00  3171.00       0.8    4055.00       4055.00


# SVM

In [123]:
# SVM
svm_param = {
    'model__C': [1, 10, 100] # np.arange(start = 1, stop = 1, step = 0.1),
    # 'kernel': ['linear', 'rbf']
    }

In [126]:
SVC_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(class_weight = 'balanced', kernel = 'rbf'))
])

BestSVC = GridSearchCV(
    SVC_pipe,
    param_grid = svm_param,
    scoring = 'f1',
    cv = stratifiedCV,
    verbose = 1,
    n_jobs = -1
)

In [127]:
BestSVC.fit(X_10_train, y_10_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        SVC(class_weight='balanced'))]),
             n_jobs=-1, param_grid={'model__C': [1, 10, 100]}, scoring='f1',
             verbose=1)

In [128]:
print(BestSVC.best_params_)
print(BestSVC.best_score_)

{'model__C': 10}
0.7573708483689301


In [129]:
y_10_BestSVCpred = BestSVC.predict(X_10_test)

print(confusion_matrix(y_10_test, y_10_BestSVCpred))
print(pd.DataFrame(classification_report(
    y_10_test, y_10_BestSVCpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[2318 1326]
 [2316 5630]]
            no aki      aki  accuracy  macro avg  weighted avg
precision     0.50     0.81      0.69       0.65          0.71
recall        0.64     0.71      0.69       0.67          0.69
f1-score      0.56     0.76      0.69       0.66          0.69
support    3644.00  7946.00      0.69   11590.00      11590.00


In [130]:
BestSVC.fit(X_50_train, y_50_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits


GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        SVC(class_weight='balanced'))]),
             n_jobs=-1, param_grid={'model__C': [1, 10, 100]}, scoring='f1',
             verbose=1)

In [131]:
print(BestSVC.best_params_)
print(BestSVC.best_score_)

{'model__C': 100}
0.8329237565957466


In [132]:
y_50_BestSVCpred = BestSVC.predict(X_50_test)
print(confusion_matrix(y_50_test, y_50_BestSVCpred))
print(pd.DataFrame(classification_report(
    y_50_test, y_50_BestSVCpred, labels = None,
    target_names = ['no aki', 'aki'], sample_weight = None,
    digits = 2, output_dict = True)).round(2))

[[ 314  570]
 [ 513 2658]]
           no aki      aki  accuracy  macro avg  weighted avg
precision    0.38     0.82      0.73        0.6          0.73
recall       0.36     0.84      0.73        0.6          0.73
f1-score     0.37     0.83      0.73        0.6          0.73
support    884.00  3171.00      0.73     4055.0       4055.00
